from enum import Enum


class UserRole(str, Enum):
    PROCUREMENT_OFFICER = "PROCUREMENT_OFFICER"
    APPROVER = "APPROVER"
    VIEWER = "VIEWER"


class ProcurementStage(str, Enum):
    RFP = "RFP"
    PROPOSAL_INTAKE = "PROPOSAL_INTAKE"
    EVALUATION = "EVALUATION"
    CONTRACT = "CONTRACT"
    FINALIZED = "FINALIZED"


class ProcurementStatus(str, Enum):
    ACTIVE = "ACTIVE"
    COMPLETED = "COMPLETED"
    CANCELLED = "CANCELLED"


class RFPStatus(str, Enum):
    DRAFT = "DRAFT"
    IN_REVIEW = "IN_REVIEW"
    APPROVED = "APPROVED"
    REJECTED = "REJECTED"
    ESCALATED = "ESCALATED"


class ProposalStatus(str, Enum):
    SUBMITTED = "SUBMITTED"
    PROCESSING = "PROCESSING"
    EXTRACTED = "EXTRACTED"
    EXTRACTION_FAILED = "EXTRACTION_FAILED"
    PARTIAL_EXTRACTION = "PARTIAL_EXTRACTION"
    UNDER_REVIEW = "UNDER_REVIEW"
    ACCEPTED = "ACCEPTED"
    REJECTED = "REJECTED"


class EvaluationStatus(str, Enum):
    PENDING = "PENDING"
    IN_PROGRESS = "IN_PROGRESS"
    AWAITING_APPROVAL = "AWAITING_APPROVAL"
    APPROVED = "APPROVED"
    REEVALUATION_REQUESTED = "REEVALUATION_REQUESTED"


class ContractStatus(str, Enum):
    DRAFT = "DRAFT"
    IN_REVIEW = "IN_REVIEW"
    APPROVED = "APPROVED"
    REJECTED = "REJECTED"
    FINALIZED = "FINALIZED"


class ApprovalActionType(str, Enum):
    APPROVED = "APPROVED"
    REJECTED = "REJECTED"
    REVISION_REQUESTED = "REVISION_REQUESTED"
    REEVALUATION_REQUESTED = "REEVALUATION_REQUESTED"
    MANUAL_OVERRIDE = "MANUAL_OVERRIDE"


class WorkflowType(str, Enum):
    RFP = "RFP"
    PROPOSAL_INTAKE = "PROPOSAL_INTAKE"
    EVALUATION = "EVALUATION"
    CONTRACT = "CONTRACT"


class WorkflowRunStatus(str, Enum):
    PENDING = "PENDING"
    RUNNING = "RUNNING"
    INTERRUPTED = "INTERRUPTED"
    COMPLETED = "COMPLETED"
    FAILED = "FAILED"


class WorkflowEventType(str, Enum):
    NODE_START = "NODE_START"
    NODE_END = "NODE_END"
    INTERRUPT = "INTERRUPT"
    RESUME = "RESUME"
    ERROR = "ERROR"
    STREAM_CHUNK = "STREAM_CHUNK"
    VALIDATION_RETRY = "VALIDATION_RETRY"
    WORKFLOW_COMPLETE = "WORKFLOW_COMPLETE"
